version: '3'
services:
  web:
    image: "node:8.12.0"
    ports:
      - "4000:4000"
    volumes:
      - ".:/usr/src/app"
    working_dir: "/usr/src/app"
    command: /bin/sh -c "apt-get update && apt-get install -y graphicsmagick && yarn && yarn develop"
